version: 0.0.1
name: 'Offline Met Studies'

input:
  files:
      # Single Muons
      # -   root://eoscms.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/safarzad/2017/SingleMuon/Collision2017-wRECO-l1t-integration-v96p27/SingleMuon/crab_Collision2017-wRECO-l1t-integration-v96p27__SingleMuon/170818_102121/000*/L1Ntuple_*.root
      # -   root://eoscms.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/safarzad/2017/SingleMuon/Fill*/Collision2017-wRECO-l1t-integration-v96p27_CaloMode/SingleMuon/crab_Collision2017-wRECO-l1t-integration-v96p27_CaloMode__SingleMuon/*/0000/L1Ntuple_*root
      # -   root://eoscms.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/safarzad/2017/SingleMuon/Collision2017-wRECO-l1t-integration-v96p27_NoPUS/SingleMuon/crab_Collision2017-wRECO-l1t-integration-v96p27_NoPUS__SingleMuon/170828_103245/0000/L1Ntuple*.root
       -   root://eoscms.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/safarzad/2017/wRECO-l1t-v96p27/SingleMuon/crab_wRECO-l1t-v96p27__Run*/*/000*/L1Ntuple_*root
      # Zero Bias
      # -  root://eoscms.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/safarzad/2017/ZeroBias/Fill6*/Collision2017-noRECO-l1t-integration-96p27_NoPUS/ZeroBias/crab_Collision2017-noRECO-l1t-integration-96p27_NoPUS__ZeroBias_Run2017C/*/0000/L1Ntuple_*root
      # -  root://eoscms.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/safarzad/2017/ZeroBias/Collision2017-noRECO-l1t-integration-96p20/ZeroBias/crab_Collision2017-noRECO-l1t-integration-96p20__ZeroBias_Run2017C/170726_094745/0000/*root
  sample:
    name: Data
    title: 2017 Data
  trigger:
    # name: ZeroBias
    # title: Zero Bias
    name: SingleMu
    title: Single Muon
  pileup_file: ""
  run_number: 6XXX

analysis:
  do_fit: True
  pu_type: 0PU12,13PU19,20PU
  pu_bins: 0,13,20,999
  analyzers:
      - cmsl1t.analyzers.offline_met_analyzer
  modifiers: []
  progress_bar:
    report_every: 1000

output:
  template:
     - output/offline_met_studies
     - "{date}_Fill-{run_number}_{sample_name}_{trigger_name}"
